INSTITUICOES = {
	'333' : 'Centro de Saúde Monção (SUB - Unidade Local de Saúde do Alto Minho, EPE)',
	'580' : 'Centro de Saúde de Albufeira (SUB - Centro Hospitalar do Algarve, EPE)',
	'587' : 'Centro de Saúde de Loulé (SUB - Centro Hospitalar do Algarve, EPE)',
	'266' : 'Centro de Saúde de Mogadouro',
	'577' : 'Centro de Saúde de Ponte de Sor (SUB - Unidade Local de Saúde do Norte Alentejano, EPE)',
	'405' : 'Centro de Saúde de Vila Nova de Foz Côa (SUB - Unidade Local de Saúde da Guarda, EPE)',
	'5687' : 'Centro de Saúde de Vila Real de Santo António (SUB - Centro Hospitalar do Algarve, EPE)',
	'171' : 'Hospitais da Universidade de Coimbra (Centro Hospitalar e Universitário de Coimbra, EPE) ',
	'173' : 'Hospital Amato Lusitano - Castelo Branco (Unidade Local de Saúde de Castelo Branco, EPE)',
	'75458' : 'Hospital Beatriz Ângelo',
	'174' : 'Hospital Bernardino Lopes de Oliveira - Alcobaça (Centro Hospitalar de Leiria, EPE) ',
	'138' : 'Hospital Conde de Bertiandos - Ponte de Lima (Unidade Local do Alto Minho, EPE)',
	'182' : 'Hospital Conde de Sucena – Águeda',
	'175' : 'Hospital Cândido de Figueiredo - Tondela (Centro Hospitalar Tondela-Viseu, EPE)',
	'2564' : 'Hospital Distrital Caldas da Rainha (Centro Hospitalar do Oeste) ',
	'181' : 'Hospital Distrital Figueira da Foz, EPE',
	'186' : 'Hospital Distrital Pombal (Centro Hospitalar de Leiria, EPE) ',
	'220' : 'Hospital Distrital Torres Vedras (Centro Hospitalar do Oeste) ',
	'135' : 'Hospital Distrital de Bragança (Unidade Local de Saúde do Nordeste, EPE) ',
	'153' : 'Hospital Distrital de Chaves (Centro Hospitalar de Trás-os-Montes e Alto Douro, EPE)',
	'183' : 'Hospital Distrital de Lamego (Centro Hospitalar de Trás-os-Montes e Alto Douro, EPE)',
	'136' : 'Hospital Distrital de Macedo de Cavaleiros (Unidade Local de Saúde do Nordeste, EPE)',
	'137' : 'Hospital Distrital de Mirandela (Unidade Local de Saúde do Nordeste, EPE) ',
	'219' : 'Hospital Distrital de Santarém, EPE',
	'2561' : 'Hospital Distrital de Vila Nova de Gaia (Centro Hospitalar de Vila Nova de Gaia/Espinho, EPE)',
	'222' : 'Hospital Distrital do Montijo (Centro Hospitalar Barreiro Montijo, EPE)',
	'234' : 'Hospital Dr. José Maria Grande - Portalegre (Unidade Local de Saúde do Norte Alentejano, EPE)',
	'203' : 'Hospital Dr. Manoel Constâncio - Abrantes (Centro Hospitalar Médio Tejo, EPE)',
	'2562' : 'Hospital Eduardo Santos Silva (Centro Hospitalar de Vila Nova de Gaia/Espinho, EPE) ',
	'233' : 'Hospital Espírito Santo de Évora, EPE',
	'225' : 'Hospital Garcia de Orta, EPE',
	'2563' : 'Hospital Geral - Covões (Centro Hospitalar e Universitário de Coimbra, EPE)',
	'156' : 'Hospital Geral de Santo António (Centro Hospitalar do Porto, EPE)',
	'189' : 'Hospital Infante D. Pedro - Aveiro (Centro Hospitalar do Baixo Vouga, EPE)',
	'235' : 'Hospital José Joaquim Fernandes - Beja (Unidade Local de Saúde do Baixo Alentejo, EPE)',
	'221' : 'Hospital Litoral Alentejano (Unidade Local de Saúde do Litoral Alentejano, EPE) ',
	'191' : 'Hospital Nossa Senhora da Assunção - Seia (Unidade Local de Saúde da Guarda, EPE)',
	'204' : 'Hospital Nossa Senhora da Graça - Tomar (Centro Hospitalar Médio Tejo, EPE)',
	'213' : 'Hospital Nossa Senhora do Rosário (Centro Hospitalar Barreiro Montijo, EPE)',
	'155' : 'Hospital Padre Américo - Vale do Sousa (Centro Hospitalar Tâmega e Sousa, EPE)',
	'6578' : 'Hospital Pedro Hispano (Unidade Local de Saúde de Matosinhos, EPE)',
	'223' : 'Hospital Professor Doutor Fernando Fonseca, EPE',
	'2565' : 'Hospital Pêro da Covilhã (Centro Hospitalar Cova da Beira, EPE)',
	'205' : 'Hospital Rainha Santa Isabel - Torres Novas (Centro Hospitalar Médio Tejo, EPE)',
	'231' : 'Hospital Santa Luzia de Elvas (Unidade Local de Saúde do Norte Alentejano, EPE)',
	'139' : 'Hospital Santa Luzia de Viana do Castelo (Unidade Local de Saúde do Alto Minho, EPE)',
	'218' : 'Hospital Santa Maria (Centro Hospitalar de Lisboa Norte, EPE)',
	'150' : 'Hospital Santa Maria Maior, EPE - Barcelos',
	'194' : 'Hospital Sousa Martins - Guarda (Unidade Local de Saúde da Guarda, EPE)',
	'215' : 'Hospital São Bernardo (Centro Hospitalar de Setúbal, EPE)',
	'216' : 'Hospital São Francisco Xavier (Centro Hospitalar de Lisboa Ocidental, EPE)',
	'151' : 'Hospital São Gonçalo - Amarante (Centro Hospitalar Tâmega e Sousa, EPE)',
	'211' : 'Hospital São José (Centro Hospitalar Lisboa Central, EPE)',
	'146' : 'Hospital São João (Centro Hospitalar de São João, EPE)',
	'184' : 'Hospital São Miguel - Oliveira de Azeméis (Centro Hospitalar Entre o Douro e Vouga, EPE)',
	'177' : 'Hospital São Pedro Gonçalves Telmo - Peniche (Centro Hospitalar do Oeste) ',
	'145' : 'Hospital São Pedro de Vila Real (Centro Hospitalar de Trás-os-Montes e Alto Douro, EPE)',
	'178' : 'Hospital São Sebastião (Centro Hospitalar de Entre o Douro e Vouga, EPE)',
	'179' : 'Hospital São Teotónio - Viseu (Centro Hospitalar Tondela-Viseu, EPE)',
	'214' : 'Hospital Vila Franca de Xira',
	'2076' : 'Hospital da Póvoa de Varzim (Centro Hospitalar Póvoa de Varzim/Vila do Conde, EPE)',
	'152' : 'Hospital da Senhora da Oliveira Guimarães, EPE ',
	'149' : 'Hospital de Braga',
	'65413' : 'Hospital de Cascais Dr. José de Almeida',
	'147' : 'Hospital de Famalicão (Centro Hospitalar do Médio Ave, EPE)',
	'236' : 'Hospital de Faro (Centro Hospitalar do Algarve, EPE) ',
	'237' : 'Hospital de Lagos (Centro Hospitalar do Algarve, EPE) ',
	'238' : 'Hospital de Portimão (Centro Hospitalar do Algarve, EPE) ',
	'180' : 'Hospital de Santo André - Leiria (Centro Hospitalar de Leiria, EPE) ',
	'141' : 'Hospital de Santo Tirso (Centro Hospitalar do Médio Ave, EPE)',
	'172' : 'Maternidade Dr. Daniel de Matos (Centro Hospitalar e Universitário de Coimbra, EPE) ',
	'160' : 'Maternidade Júlio Dinis',
	'2067106' : 'Centro de Medicina de Reabilitação da Região Centro – Rovisco Pais',
	'541' : 'Centro de Saúde Castro Verde (SUB - Unidade Local de Saúde do Baixo Alentejo, EPE)',
	'545' : 'Centro de Saúde Moura (SUB - Unidade Local de Saúde do Baixo Alentejo, EPE)',
	'517' : 'Centro de Saúde de Alcácer do Sal',
	'362' : 'Centro de Saúde de Arganil',
	'344' : 'Centro de Saúde de Arouca',
	'428' : 'Centro de Saúde de Cinfães',
	'553' : 'Centro de Saúde de Estremoz',
	'431' : 'Centro de Saúde de Moimenta da Beira',
	'318' : 'Centro de Saúde de Montalegre',
	'555' : 'Centro de Saúde de Montemor-o-Novo',
	'546' : 'Centro de Saúde de Odemira',
	'439' : 'Centro de Saúde de São Pedro do Sul',
	'187' : 'Hospital Arcebispo João Crisóstomo - Cantanhede',
	'185' : 'Hospital Distrital São João da Madeira (Centro Hospitalar de Entre o Douro e Vouga, EPE)',
	'142' : 'Hospital Dom Luiz I - Peso da Régua (Centro Hospitalar de Trás-os-Montes e Alto Douro, EPE)',
	'208' : 'Hospital Dona Estefânia (Centro Hospitalar Lisboa Central, EPE)',
	'188' : 'Hospital Dr. Francisco Zagalo - Ovar',
	'212' : 'Hospital Egas Moniz (Centro Hospitalar de Lisboa Ocidental, EPE)',
	'157' : 'Hospital Joaquim Urbano (Centro Hospitalar do Porto, EPE)',
	'190' : 'Hospital José Luciano de Castro - Anadia',
	'201' : 'Hospital Júlio de Matos (Centro Hospitalar Psiquiátrico de Lisboa)',
	'144' : 'Hospital Nossa Senhora da Conceição de Valongo (Centro Hospitalar de São João, EPE)',
	'226' : 'Hospital Ortopédico Sant\'Iago do Outão (Centro Hospitalar de Setúbal, EPE)',
	'168' : 'Hospital Pediátrico de Coimbra (Centro Hospitalar e Universitário de Coimbra, EPE) ',
	'193' : 'Hospital Psiquiátrico Sobral Cid (Centro Hospitalar e Universitário de Coimbra, EPE) ',
	'227' : 'Hospital Pulido Valente (Centro Hospitalar de Lisboa Norte, EPE)',
	'217' : 'Hospital Santa Cruz (Centro Hospitalar de Lisboa Ocidental, EPE)',
	'209' : 'Hospital Santa Marta (Centro Hospitalar Lisboa Central, EPE)',
	'210' : 'Hospital Santo António dos Capuchos (Centro Hospitalar Lisboa Central, EPE)',
	'232' : 'Hospital São Paulo - Serpa',
	'165' : 'Hospital Termal Rainha D. Leonor (Centro Hospitalar do Oeste) ',
	'195' : 'Hospital Visconde de Salreu - Estarreja (Centro Hospitalar do Baixo Vouga, EPE)',
	'206' : 'Hospital de Curry Cabral (Centro Hospitalar Lisboa Central, EPE)',
	'143' : 'Hospital de Magalhães Lemos, EPE',
	'2077' : 'Hospital de Vila do Conde (Centro Hospitalar Póvoa de Varzim/Vila do Conde, EPE)',
	'2566' : 'Hospital do Fundão (Centro Hospitalar Cova da Beira, EPE)',
	'196' : 'Instituto Português de Oncologia de Coimbra Francisco Gentil, EPE',
	'228' : 'Instituto Português de Oncologia de Lisboa Francisco Gentil, EPE',
	'159' : 'Instituto Português de Oncologia de Porto Francisco Gentil, EPE',
	'2006' : 'Instituto de Oftalmologia Dr. Gama Pinto',
	'169' : 'Maternidade Bissaya Barreto (Centro Hospitalar e Universitário de Coimbra, EPE) ',
	'229' : 'Maternidade Dr. Alfredo da Costa (Centro Hospitalar Lisboa Central, EPE)',
}